version = 0.1

default-task = 'build'

[env]
CARGO_BUILD_TARGET = 'wasm32-unknown-emscripten'
CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUNNER = 'node'
CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUSTFLAGS="-Clink-arg=-sJSPI -Clink-arg=-sALLOW_MEMORY_GROWTH"
RUST_BACKTRACE = '1'

[[task]]
name = 'build'
run = 'cargo build'

[[task]]
name = 'test'
deps = [
  'test:debug',
]

[[task]]
name = 'test:debug'
run = 'cargo test'
